# Generated by Django 4.2.6 on 2023-10-24 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('iputdata', models.CharField(max_length=255)),
                ('outputdata', models.CharField(max_length=255)),
                ('result', models.TextField()),
            ],
            options={
                'verbose_name': 'интерпретатор',
                'verbose_name_plural': 'не подлежит редактированию',
            },
        ),
        migrations.CreateModel(
            name='TestCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('TaskDescription', models.TextField(verbose_name='Описание задания')),
                ('task_variables', models.CharField(max_length=256, verbose_name='Переменные')),
            ],
            options={
                'verbose_name': 'Задачу',
                'verbose_name_plural': 'Список задач',
            },
        ),
        migrations.CreateModel(
            name='UserCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('iputdata', models.CharField(max_length=255)),
                ('outputdata', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Пользовательский код',
                'verbose_name_plural': 'Пользовательские коды',
            },
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vvod', models.TextField(verbose_name='Вводные данные')),
                ('RightRes', models.TextField(verbose_name='Правильный ответ')),
                ('outputdata', models.TextField(blank=True, null=True, verbose_name='Выходные данные')),
                ('Result', models.BooleanField(blank=True, null=True, verbose_name='Результат')),
                ('test_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testdata', to='interpreter.testcode', verbose_name='Связь с задачей')),
            ],
            options={
                'verbose_name': 'Тестовые данные',
                'verbose_name_plural': 'Тестовые данные',
            },
        ),
    ]
